### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yahyamokaied** [AgoraIO-Community/VideoUIKit-Flutter#105]
**Describe the bug**
In Agora_UIKit Getting error When trying to click on endCall it  and it doesn't go back to the previous screen

**Expected behavior**
It goes back to previous screen and close the channel/session successfully 

**Smartphone (please complete the following information):**
 - Device: iPhone Xs Max
 - OS: iOS 15.6.1

**Additional context**
Tried with and without OnDisconnect  but it still the same error 102

**Screenshots**
<img width="954" alt="Screenshot 2022-10-06 at 00 44 23" src="https://user-images.githubusercontent.com/50097658/194177299-4d7d4fcc-71e5-4a03-ac08-00411d2c1ba6.png">

<img width="954" alt="Screenshot 2022-10-06 at 00 48 31" src="https://user-images.githubusercontent.com/50097658/194177751-5ad249d6-a851-4a23-8411-326280a4971b.png">

**Comment by Meherdeep** [comment]
You can ignore the error that you shared. To navigate the screen to the previous page or to add any other function to the end call button you can use the `onDisconnect` method in the `AgoraVideoButton` class and specify how you want the button to behave.
