### ISSUE TITLE
agora_uikit: ^1.0.4 is incompatible with agora_rtc_engine: ^6.0.0

### ISSUE THREAD

**Issue by waqadArshad** [AgoraIO-Community/VideoUIKit-Flutter#106]
@Meherdeep @maxxfrazer @Ascenio @hxingpax 
while updating the dependencies, I am getting this issue.
agora_uikit: ^1.0.4 is incompatible with agora_rtc_engine: ^6.0.0 because agora_uikit: ^1.0.4 is still using the older 5.0.2 version

**Comment by maxxfrazer** [comment]
Hi @waqadArshad, thanks for the message!

We're aware of this and an updated version is underway on this branch:

https://github.com/AgoraIO-Community/VideoUIKit-Flutter/tree/ngsdk-release


When updating to use that SDK, the changes for devs using the Flutter Video UI Kit will be very minor, despite RTC 6.x being very different from 5.x

**Comment by waqadArshad** [comment]
@maxxfrazer so does this mean I should use 5.0.2 for now?

**Comment by Meherdeep** [comment]
@waqadArshad Please use the updated v1.1.0
