### ISSUE TITLE
How to call directly like Whatsapp using this package ? 

### ISSUE THREAD

**Issue by arslankaleem7229** [AgoraIO-Community/VideoUIKit-Flutter#107]
I want to integrate direct calling like WhatsApp and second person should be able to see notification of call where he/she can accept/reject. But I didn't find such functionality here. So is there any functionality like this ?

**Comment by fisforfaheem** [comment]
following

**Comment by Meherdeep** [comment]
@arslankaleem7229 @fisforfaheem UIKit allows you to add video calling features like WhatsApp. But if you want to add notification you will have to use Connection Service/Callkit with your flutter application.

**Comment by tadaspetra** [comment]
Closing issue, please reopen if it's not solved
