### ISSUE TITLE
Please add FLutter  web support it would help us extend the app

### ISSUE THREAD

**Issue by fisforfaheem** [AgoraIO-Community/VideoUIKit-Flutter#110]
Can you please add flutter web support?

**Comment by maxxfrazer** [comment]
Web support would be needed in both [Agora-Flutter-SDK](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK) and [Agora-Flutter-RTM-SDK](https://github.com/AgoraIO/Agora-Flutter-RTM-SDK) before it could be added to the Video UI Kit.
