### ISSUE TITLE
[BUG]     Audio Of both side is working in my Case but no user id or video is showing 

### ISSUE THREAD

**Issue by FlutterDev02** [AgoraIO-Community/VideoUIKit-Flutter#111]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by maxxfrazer** [comment]
Hi @FlutterDev02, could you fill out the issue with a little more details as outlined in the template?

**Comment by Meherdeep** [comment]
@FlutterDev02 Can you please share the code that you're using?

**Comment by Meherdeep** [comment]
@FlutterDev02 Closing this issue for now, if you are still facing the issue feel free to reopen it.

**Comment by fisforfaheem** [comment]
moved to zego cloud, where its 10 times easier.
