### ISSUE TITLE
Is there option to get notification like whatsapp give us incoming call ?[FEATURE]

### ISSUE THREAD

**Issue by dishantCWeapplinse** [AgoraIO-Community/VideoUIKit-Flutter#120]
I just thinking is this possible when other user call us we have notification like whatsapp (when voice call or video call from other user) when our app is in kill mode (Means not open ) ?

**Comment by Meherdeep** [comment]
@dishantCWeapplinse The UIKit doesn't provide a notification service as of now. You will need to integrate connection service and CallKit to your application for this.

**Comment by Srj-Love** [comment]
Hey @meherdeep, could you please share any doc or code where I can check with calls notification.

**Comment by Meherdeep** [comment]
@Srj-Love You can refer to this doc: https://docs.agora.io/en/signaling/develop/call-invite-notification?platform=android
