### ISSUE TITLE
AgoraRtcEventHandlers callback are called multiple times

### ISSUE THREAD

**Issue by adiShinwari** [AgoraIO-Community/VideoUIKit-Flutter#124]
When the user joined the channel or leave the channel the callbacks method called several time. I have to update the nodes in firebase. how can I handle this, because of the issue, the data is updating several times.
**To Reproduce**
using the simple code from example in agora_uikit pub.dev

**Smartphone (please complete the following information):**
 iPhone 11

**Comment by Meherdeep** [comment]
@adiShinwari  Can you please share your log file. 
Also, while adding/removing data from firebase can you do a check for `uid` first, if it already exists or not.
