### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ardeshir-33033** [AgoraIO-Community/VideoUIKit-Flutter#135]
Hello I am using 
   agora_uikit: ^1.3.2
   
   and all of a sudden I have this error
   
       : Error: The argument type 'VideoSourceType' can't be assigned to the parameter type 'RtcConnection'.
    rtc_event_handlers.dart:65
    - 'VideoSourceType' is from 'package:agora_rtc_engine/src/agora_base.dart' ('../../.pub-cache/hosted/pub.dev/agora_rtc_engine-6.1.1/lib/src/agora_base.dart').
    agora_base.dart:1
    - 'RtcConnection' is from 'package:agora_rtc_engine/src/agora_rtc_engine_ex.dart' ('../../.pub-cache/hosted/pub.dev/agora_rtc_engine-6.1.1/lib/src/agora_rtc_engine_ex.dart').
    agora_rtc_engine_ex.dart:1
            ?.call(connection, width, height, elapsed);
                   ^
    Target kernel_snapshot failed: Exception

**Comment by ardeshir-33033** [comment]
i have an update on this.
when I add 
agora_rtc_engine: 6.1.0 to my project this error is fixed.
it does not work with version 6.1.1.

**Comment by GhulamZakariya** [comment]
> i have an update on this. when I add agora_rtc_engine: 6.1.0 to my project this error is fixed. it does not work with version 6.1.1.

but i add this still same error

Error: The argument type 'VideoSourceType' can't be assigned to the parameter type 'RtcConnection'.
 - 'VideoSourceType' is from 'package:agora_rtc_engine/src/agora_base.dart' ('../../../../.pub-cache/hosted/pub.dev/agora_rtc_engine-6.1.1/lib/src/agora_base.dart').
 - 'RtcConnection' is from 'package:agora_rtc_engine/src/agora_rtc_engine_ex.dart' ('../../../../.pub-cache/hosted/pub.dev/agora_rtc_engine-6.1.1/lib/src/agora_rtc_engine_ex.dart').
        ?.call(connection, width, height, elapsed);

**Comment by ardeshir-33033** [comment]
> > i have an update on this. when I add agora_rtc_engine: 6.1.0 to my project this error is fixed. it does not work with version 6.1.1.
> 
> but i add this still same error
> 
> Error: The argument type 'VideoSourceType' can't be assigned to the parameter type 'RtcConnection'.
> 
> * 'VideoSourceType' is from 'package:agora_rtc_engine/src/agora_base.dart' ('../../../../.pub-cache/hosted/pub.dev/agora_rtc_engine-6.1.1/lib/src/agora_base.dart').
> * 'RtcConnection' is from 'package:agora_rtc_engine/src/agora_rtc_engine_ex.dart' ('../../../../.pub-cache/hosted/pub.dev/agora_rtc_engine-6.1.1/lib/src/agora_rtc_engine_ex.dart').
>   ?.call(connection, width, height, elapsed);

Ghulam Are you sure agora_rtc_engine version is set back to 6.1.0?
Because it seems not.
to make sure go over pubspec.lock and search for agora_rtc_engine 
you can see its version there.
