### ISSUE TITLE
when layoutType is floating, i got this error

### ISSUE THREAD

**Issue by kyawthet-wam** [AgoraIO-Community/VideoUIKit-Flutter#137]
Exception caught by widgets library ═══════════════════════════════════
Remote uid can not be null or 0
'package:agora_rtc_engine/src/render/video_view_controller.dart':
video_view_controller.dart:1
Failed assertion: line 74 pos 16: 'canvas.uid != null && canvas.uid != 0'

**Comment by Meherdeep** [comment]
Hey @kyawthet-wam, 

Thanks for reporting the issue. We'll release a fix for this soon.

**Comment by kyawthet-wam** [comment]
the same issue when I pinned the remote user.
