### ISSUE TITLE
Cannot build apk file "Null Function(LocalInvitation)" [BUG]

### ISSUE THREAD

**Issue by RemigijusD** [AgoraIO-Community/VideoUIKit-Flutter#139]
While trying to run flutter build apk --release, the process finishes with a problem indicating that there might be an issue with agora rtm_client_event_handler.dart:76:7. I tried to resolve it changing build gradles and kotlin version, but with no success. 

To reproduce the bug:
have these in the pubspec.yaml:
agora_uikit: ^1.3.3
permission_handler: ^10.2.0

try to run flutter build apk --release in the terminal.

Then it the console log output looks like this:

`Running Gradle task 'assembleRelease'...                        
/C:/Users/remig/AppData/Local/Pub/Cache/hosted/pub.dev/agora_uikit-1.3.3/lib/controllers/rtm_client_event_handler.dart:76:7: Error: A value of type 'Null Function(LocalInvitation)' can't be assigned to a variable of type 'dynamic Function(LocalInvitation, String)?'.
 - 'LocalInvitation' is from 'package:agora_rtm/src/utils.dart' ('/C:/Users/remig/AppData/Local/Pub/Cache/hosted/pub.dev/agora_rtm-1.5.1/lib/src/utils.dart').
      (AgoraRtmLocalInvitation invitation) {
      ^
/C:/Users/remig/AppData/Local/Pub/Cache/hosted/pub.dev/agora_uikit-1.3.3/lib/controllers/rtm_client_event_handler.dart:81:7: Error: A value of type 'void Function(LocalInvitation)' can't be assigned to a variable of type 'void Function(LocalInvitation, String)?'.
 - 'LocalInvitation' is from 'package:agora_rtm/src/utils.dart' ('/C:/Users/remig/AppData/Local/Pub/Cache/hosted/pub.dev/agora_rtm-1.5.1/lib/src/utils.dart').
      (AgoraRtmLocalInvitation invitation) {
      ^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1201

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
Running Gradle task 'assembleRelease'...                           22.9s
Gradle task assembleRelease failed with exit code 1`

Additional information:
build gradle: classpath 'com.android.tools.build:gradle:7.1.2'
wrapper distribution url: distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-all.zip

Some help or guidance would be appreciated :)

**Comment by abeloha** [comment]
I am having same issue. Please what is the solution?

**Comment by mjmon** [comment]
same issue with ios release build

**Comment by codeyq** [comment]
+1 on same issue. Could you help take a look? @tadaspetra

**Comment by tadaspetra** [comment]
We're looking into this. Will push an update soon!

**Comment by RemigijusD** [comment]
> We're looking into this. Will push an update soon!

Thanks @tadaspetra , looking forward to it, ačiū!

**Comment by ardeshir-33033** [comment]
any updates on this?

**Comment by tadaspetra** [comment]
It's being tracked in #138

**Comment by tadaspetra** [comment]
New version has been released. Version `1.3.4`

This should solve the problem. Please reopen if it doesn'

**Comment by tadaspetra** [comment]
Version 1.3.5 has just been released with a wider version of `http`

> So 1.3.4 does not resolve the issue because you've now moved to http 1.0.0. Why ? From one issue to another. guys you can't do this, this is bad programming practice. http 1.0.0 is very new and most libs don't use it yet. Its causing issues with my other packages that are not yet compatible with http 1.0.0.
> 
> PLease revert the http 1.0.0 upgrade and fix the bug. Its much wiser moving to http 1.0 with agora_uikit 2.0.0 instead of 1.3.4
