### ISSUE TITLE
The example keeps loading...

### ISSUE THREAD

**Issue by BlackTryyy** [AgoraIO-Community/VideoUIKit-Flutter#145]
I added the following in android\app\build.gradle
```
allprojects {
	repositories {
		maven { url 'https://jitpack.io' }
	}
}
```
I added the following in android\app\src\main\AndroidManifest.xml
```
<uses-permission  android:name="android.permission.READ_PHONE_STATE"/>
<uses-permission  android:name="android.permission.INTERNET"  />
<uses-permission  android:name="android.permission.RECORD_AUDIO"  />
<uses-permission  android:name="android.permission.CAMERA"  />
<uses-permission  android:name="android.permission.MODIFY_AUDIO_SETTINGS"  />
<uses-permission  android:name="android.permission.ACCESS_NETWORK_STATE"  />
```
The latest versions of dart and flutter were used
```
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  agora_uikit: ^1.3.4
flutter:
  uses-material-design: true
```
```
import 'package:flutter/material.dart';
import 'package:agora_uikit/agora_uikit.dart';

void main() {
  runApp(const MyApp());
}

AgoraClient client = AgoraClient(
  // 连接
  agoraConnectionData:
      AgoraConnectionData(appId: appId, channelName: channelName),
  // 权限
  enabledPermission: [
    Permission.camera,
    Permission.microphone,
  ],
);
// 定义 App ID、Token 和 Channel
const appId = "a9d1e6e203f94c55a3e3088be078aaed";
const token =
    "007eJxTYFgfe26z255Mba/3U9+0dNToRD3sZfTL+q4g//ZJrKxPvoACQ6JlimGqWaqRgXGapUmyqWmicaqxgYVFUqqBuUViYmrKhCuTUhoCGRlkBSayMDJAIIjPwZCUk5icXVJUycAAANugIOg=";
const channelName = "blacktry";

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Material(
      child: MaterialApp(
        home: Scaffold(
          body: Center(
            child: Stack(
              children: [AgoraVideoViewer(client: client)],
            ),
          ),
        ),
      ),
    );
  }
}
```
millions of thanks！！！

![9E9646A92978944C8C793A825CE60401](https://github.com/AgoraIO-Community/VideoUIKit-Flutter/assets/131345116/cf6ed9db-4ea8-4e9c-9320-33895479d1f5)

**Comment by Meherdeep** [comment]
@BlackTryyy Can you please share the SDK logs

**Comment by BlackTryyy** [comment]
> @BlackTryyy Can you please share the SDK logs
[thank you for response](javascript:;)


I/Gralloc4(22638): mapper 4.x is not supported
W/Gralloc3(22638): mapper 3.x is not supported
I/ideo_test_uiki(22638): ProcessProfilingInfo new_methods=1051 is saved saved_to_disk=1 resolve_classes_delay=8000
D/MIUIInput(22638): [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_UP, keyCode=KEYCODE_VOLUME_DOWN, scanCode=114, metaState=0, flags=0x8, repeatCount=0, eventTime=112452006, downTime=110908657, deviceId=4, source=0x101, displayId=-1 }
D/MIUIInput(22638): [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_VOLUME_DOWN, scanCode=114, metaState=0, flags=0x8, repeatCount=0, eventTime=112452068, downTime=112452068, deviceId=4, source=0x101, displayId=-1 }
W/InputTransport(22638): Slow Input: 152ms so far, channel 'ClientState{3512eb3 uid=10008 pid=22638 displayId=0} (server)' publisher ~ publishKeyEvent: seq=2180, deviceId=4, source=0x101, action=0x0, flags=0x8, keyCode=25, scanCode=114, metaState=0x0, repeatCount=0,downTime=112452068000000, eventTime=112452068000000
W/MirrorManager(22638): this model don't Support
D/MIUIInput(22638): [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_VOLUME_DOWN, scanCode=114, metaState=0, flags=0x88, repeatCount=1, eventTime=112452469, downTime=112452068, deviceId=4, source=0x101, displayId=-1 }
D/MIUIInput(22638): [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_VOLUME_DOWN, scanCode=114, metaState=0, flags=0x8, repeatCount=2, eventTime=112452520, downTime=112452068, deviceId=4, source=0x101, displayId=-1 }
D/MIUIInput(22638): [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_VOLUME_DOWN, scanCode=114, metaState=0, flags=0x8, repeatCount=3, eventTime=112452571, downTime=112452068, deviceId=4, source=0x101, displayId=-1 }
D/MIUIInput(22638): [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_VOLUME_DOWN, scanCode=114, metaState=0, flags=0x8, repeatCount=4, eventTime=112452622, downTime=112452068, deviceId=4, source=0x101, displayId=-1 }
D/MIUIInput(22638): [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_VOLUME_DOWN, scanCode=114, metaState=0, flags=0x8, repeatCount=5, eventTime=112452672, downTime=112452068, deviceId=4, source=0x101, displayId=-1 }
D/MIUIInput(22638): [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_UP, keyCode=KEYCODE_VOLUME_DOWN, scanCode=114, metaState=0, flags=0x8, repeatCount=0, eventTime=112470250, downTime=112452068, deviceId=4, source=0x101, displayId=-1 }
D/MIUIInput(22638): [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_VOLUME_DOWN, scanCode=114, metaState=0, flags=0x8, repeatCount=0, eventTime=112470311, downTime=112470311, deviceId=4, source=0x101, displayId=-1 }
W/InputTransport(22638): Slow Input: 151ms so far, channel 'ClientState{3512eb3 uid=10008 pid=22638 displayId=0} (server)' publisher ~ publishKeyEvent: seq=2532, deviceId=4, source=0x101, action=0x0, flags=0x8, keyCode=25, scanCode=114, metaState=0x0, repeatCount=0,downTime=112470311000000, eventTime=112470311000000
D/MIUIInput(22638): [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_VOLUME_DOWN, scanCode=114, metaState=0, flags=0x88, repeatCount=1, eventTime=112470712, downTime=112470311, deviceId=4, source=0x101, displayId=-1 }
D/MIUIInput(22638): [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_VOLUME_DOWN, scanCode=114, metaState=0, flags=0x8, repeatCount=2, eventTime=112470763, downTime=112470311, deviceId=4, source=0x101, displayId=-1 }
D/MIUIInput(22638): [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_VOLUME_DOWN, scanCode=114, metaState=0, flags=0x8, repeatCount=3, eventTime=112470814, downTime=112470311, deviceId=4, source=0x101, displayId=-1 }
D/MIUIInput(22638): [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_VOLUME_DOWN, scanCode=114, metaState=0, flags=0x8, repeatCount=4, eventTime=112470864, downTime=112470311, deviceId=4, source=0x101, displayId=-1 }
D/MIUIInput(22638): [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_VOLUME_DOWN, scanCode=114, metaState=0, flags=0x8, repeatCount=5, eventTime=112470914, downTime=112470311, deviceId=4, source=0x101, displayId=-1 }
Application finished.

**Comment by tadaspetra** [comment]
You never initialized the client. Before you render the VideoViewer `client.initialize()` needs to be called. You can see an example [starter project here](https://pub.dev/packages/agora_uikit/example)
