### ISSUE TITLE
How do you show other users when they join the channel

### ISSUE THREAD

**Issue by BlackTryyy** [AgoraIO-Community/VideoUIKit-Flutter#146]
How do you show other users when they join the channel，This doesn't seem to be in the quick use case, where do I need to add it, please provide me with a reference code if possible

**Comment by tadaspetra** [comment]
The UI Kit shows the other users by default. All you need is the `AgoraVideoViewer` and the users will all be shown. If you're not seeing them, make sure you are joining the same channel with different uid

**Comment by BlackTryyy** [comment]
Where can I check their uid   Thank you very much for your reply.
