### ISSUE TITLE
Details on how to properly setup screen-sharing functionality in iOS build using UIKit

### ISSUE THREAD

**Issue by mrtordoide** [AgoraIO-Community/VideoUIKit-Flutter#150]
**Is your feature request related to a problem? Please describe.**
It is not really a problem but it is quiet challenging to get the screen sharing functionality to work on iOS build

**Describe the solution you'd like**
Steps involved to setup the iOS native code and components would help a lot

**Describe alternatives you've considered**
I tried looking into documentations from Agora RTC Engine but it was quite difficult

**Additional context**
NA

**Comment by tadaspetra** [comment]
We are working on this. The iOS implementation isn't perfect right now either this is why we labeled it as a `beta`. We are working to make it function nicer and then that will release with some better documentation of how to implement

**Comment by maxxfrazer** [comment]
iOS screen sharing is a headache. if you want to try get something together before we update the library and docs we do have this Native iOS guide:
https://agoraio-community.github.io/VideoUIKit-iOS/extensions/AgoraBroadcastExtensionHelper/documentation/agorabroadcastextensionhelper/quickstart

but there’s a better method that uses a library that’s bundled with the SDK to send the stream back to the main app, we’re making those docs for all platforms soon

**Comment by amit3xpo** [comment]
Understood. Will be looking out for the updates. Thank you!
