### ISSUE TITLE
The argument type 'VideoSourceType' can't be assigned to the parameter type 'RtcConnection'

### ISSUE THREAD

**Issue by BobLee-GT** [AgoraIO-Community/VideoUIKit-Flutter#151]
../../.pub-cache/hosted/pub.dev/agora_uikit-1.3.5/lib/controllers/rtc_event_handlers.dart:66:16: Error: The argument type 'VideoSourceType' can't be assigned to the parameter type 'RtcConnection'.
 - 'VideoSourceType' is from 'package:agora_rtc_engine/src/agora_media_base.dart' ('../../.pub-cache/hosted/pub.dev/agora_rtc_engine-6.2.2/lib/src/agora_media_base.dart').
 - 'RtcConnection' is from 'package:agora_rtc_engine/src/agora_rtc_engine_ex.dart' ('../../.pub-cache/hosted/pub.dev/agora_rtc_engine-6.2.2/lib/src/agora_rtc_engine_ex.dart').
        ?.call(connection, elapsed);
               ^
../../.pub-cache/hosted/pub.dev/agora_uikit-1.3.5/lib/controllers/rtc_event_handlers.dart:120:48: Error: The argument type 'VideoSourceType' can't be assigned to the parameter type 'RtcConnection'.
 - 'VideoSourceType' is from 'package:agora_rtc_engine/src/agora_media_base.dart' ('../../.pub-cache/hosted/pub.dev/agora_rtc_engine-6.2.2/lib/src/agora_media_base.dart').
 - 'RtcConnection' is from 'package:agora_rtc_engine/src/agora_rtc_engine_ex.dart' ('../../.pub-cache/hosted/pub.dev/agora_rtc_engine-6.2.2/lib/src/agora_rtc_engine_ex.dart').
    agoraEventHandlers.onLocalVideoStats?.call(connection, stats);

**Comment by BobLee-GT** [comment]
I was research from [agora document](https://docs.agora.io/en/video-calling/get-started/get-started-uikit?platform=flutter#test-your-implementation) but at the first time I run app it show this error

**Comment by Meherdeep** [comment]
Thanks for sharing this. We will create a fix for this soon.

**Comment by maxxfrazer** [comment]
Sorry for the inconvenience @BobLee-GT. Our Flutter SDK had a breaking release in a patch update.

We're working with that team to try align on reserving these updates for minor releases (MAJOR.MINOR.PATCH) going forward.

PR #152 should be merged and published soon to fix your issue

**Comment by Meherdeep** [comment]
@BobLee-GT Please use the v1.3.6 
This should fix the above mentioned error.
