### ISSUE TITLE
On pressing the call end button it goes black screen

### ISSUE THREAD

**Issue by souravdivii** [AgoraIO-Community/VideoUIKit-Flutter#157]
The error : 
[AgoraVideoUIKit] Local video state changed, source: VideoSourceType.videoSourceCameraPrimary, state: LocalVideoStreamState.localVideoStreamStateStopped and error: LocalVideoStreamError.localVideoStreamErrorOk
E/flutter (15665): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Instance of 'AgoraRtmChannelException'

Also for some reason it shows Debug in the screen which I have made false in the main.dart file.

**Comment by Meherdeep** [comment]
After you press the end call button, the preset action turns the screen black. However, if you want to change the operation of the `endCallButton`, In the `AgoraVideoButtons` class use the `onDisconnect` method to add your desired functionality.
