### ISSUE TITLE
[BUG] how can i add event handlers please

### ISSUE THREAD

**Issue by Ahmad0Tanveer** [AgoraIO-Community/VideoUIKit-Flutter#165]
AgoraClient client = AgoraClient(
    agoraConnectionData: AgoraConnectionData(
      appId: "............ ID.............",
      channelName: "test",
      username: name,
    ),
      agoraEventHandlers: AgoraRtcEventHandlers(
        onUserJoined: (x,y,z) {
          setState(() {
            ggg = client.users.length;
          });
        }
      )
  );
 how can i create design like whats app video calling one to one calling and Joint add Users lay change to Gride

**Comment by Meherdeep** [comment]
You can take a look at this guide that explains how to add event handlers: [https://github.com/AgoraIO-Community/VideoUIKit-Flutter/wiki/Examples#accesing-agora-rtcengineeventhandlers](https://github.com/AgoraIO-Community/VideoUIKit-Flutter/wiki/Examples#accesing-agora-rtcengineeventhandlers)
