### ISSUE TITLE
BUG: Not receiving any Audio in Calls - Video is working fine

### ISSUE THREAD

**Issue by WorkWithAfridi** [AgoraIO-Community/VideoUIKit-Flutter#169]
After updating to the latest Flutter and Agora UI Kit versions (Was on Flutter 3.10 and UIKit 1.3.3), I am not receiving any audio in calls. Video is working perfectly fine, but Audio is not. Non of the volume adjustment buttons are working as well, I have to terminate the app to make the volume buttons works again.

**Comment by WorkWithAfridi** [comment]
> how to fix error, please?

My issue was related to the push notification package I used. I had to remove the push notification popup all together and show an in-app screen alerting the user of an incoming call.

**Comment by ilnhatdev** [comment]
> > how to fix error, please?
> 
> My issue was related to the push notification package I used. I had to remove the push notification popup all together and show an in-app screen alerting the user of an incoming call.

Thank you for your answer. Is there a way to keep windows running in the background and still have it active?
