### ISSUE TITLE
Reduce AppSize After Integration of Agora UIKit

### ISSUE THREAD

**Issue by nikkieke** [AgoraIO-Community/VideoUIKit-Flutter#173]
### App Size Increased to over 300mb after integration of AgoraUIKit

After Integrating AgoraUIkit for Video Call implementation in my app, App size increased from 40MB to over 300MB, please how do I reduce app size for Android & IOS?

**Screenshots**
<img width="1067" alt="Screenshot 2024-02-26 141850" src="https://github.com/AgoraIO-Community/VideoUIKit-Flutter/assets/95222620/455e0363-a755-4eb3-86f1-5578843a2d40">

**Comment by ladla8602** [comment]
You can define abiFilters in app level `android/app/build.gradle`. It will significantly reduce the app size. And for more app size reduction you need to exclude native libs file which provided by Agora if any lib that are not going to be used in your app you can exclude it.  Here is the reference - [https://docs.agora.io/en/help/integration-issues/reduce_app_size_rtc#solution-2-remove-unnecessary-extension-libraries#solution-2-remove-unnecessary-extension-libraries](https://docs.agora.io/en/help/integration-issues/reduce_app_size_rtc#solution-2-remove-unnecessary-extension-libraries#solution-2-remove-unnecessary-extension-libraries).

One more thing you can use to reduce app side is to use proguard rules.

```
buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true
            ndk {
                abiFilters 'armeabi-v7a','arm64-v8a'
                // abiFilters 'armeabi-v7a','arm64-v8a','x86_64'
            }
        }
    }
```

By just defining abiFilters my app reduces from 324MB to 171MB. So for `armeabi-v7a` cpu devices my apk size ~ 69MB and for `arm64-v8a` is around 91MB.
