### ISSUE TITLE
compileReleaseKotlin Error

### ISSUE THREAD

**Issue by osmangaziyildiz** [AgoraIO-Community/VideoUIKit-Flutter#179]
Error when trying to export the application as an aab file.

1. Go to 'terminal'
2. Run 'flutter build appbundle'
3. See error

**Screenshots**
![Ekran görüntüsü 2024-03-06 011506](https://github.com/AgoraIO-Community/VideoUIKit-Flutter/assets/47447325/393ff453-f5d9-4e94-94b4-80f7749c80b4)

**Comment by AmirK102** [comment]
Any update on this issue?
