### ISSUE TITLE
Error in upload IOS version

### ISSUE THREAD

**Issue by adham-ashraf77** [AgoraIO-Community/VideoUIKit-Flutter#203]
![WhatsApp Image 2024-10-01 at 18 09 14_5b853bcf](https://github.com/user-attachments/assets/bf04d3ca-bc74-4ff1-92df-de847aa6c69d)
I face this error since update Xcode to 16 and ios 18 can't upload the version any help please?

**Comment by adham-ashraf77** [comment]
there is a workaround in Podfile to add 
----
post_install do |installer|
     bitcode_strip_path = `xcrun --find bitcode_strip`.chop!
       def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
         framework_path = File.join(Dir.pwd, framework_relative_path)
         command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
         puts "Stripping bitcode: #{command}"
         system(command)
       end

       framework_paths = [
         "Pods/AgoraRtm/AgoraRtmKit.xcframework/ios-arm64_armv7/AgoraRtmKit.framework/AgoraRtmKit",
         "Pods/AgoraRtm/AgoraRtmKit.xcframework/macos-arm64_x86_64/AgoraRtmKit.framework/AgoraRtmKit",
         "Pods/AgoraRtm/AgoraRtmKit.xcframework/xros-arm64/AgoraRtmKit.framework/AgoraRtmKit",
         "Pods/AgoraRtm_IOS/AgoraRtmKit.xcframework/ios-arm64_armv7/AgoraRtmKit.framework/AgoraRtmKit"
       ]

       framework_paths.each do |framework_relative_path|
         strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
       end
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
------

![WhatsApp Image 2024-10-01 at 21 21 25_83f8331c](https://github.com/user-attachments/assets/79bb8553-d046-42c4-a07c-a1626ca3822c)

please update the package as soon as possible please.

Note: Bitcode is no longer supported From the Xcode 15.

**Comment by xainar** [comment]
XCode Cloud also gives me error. ITMS-90482: Invalid Executable. Please upgrade package asap.
