### ISSUE TITLE
Peer to peer video calls

### ISSUE THREAD

**Issue by SrujanMungara** [AgoraIO-Community/VideoUIKit-Flutter#93]
I have 100 users. How can I make a peer to peer calls(only between two individuals) for those users. How to differentiate channel names etc for not overlapping the calls

**Comment by SrujanMungara** [comment]
My requirement is identical to a whatsapp video/voice call. No need for the user to enter anything. I need to connect to the receiver directly.

**Comment by arslankaleem7229** [comment]
@SrujanMungara  seems like your requirements are the same as mine. I want to integrate direct video calls like WhatsApp but right now I am unable to find such a thing. Is this your problem statement? And did you find anything?

**Comment by Meherdeep** [comment]
@SrujanMungara @arslankaleem7229 The user doesn't necessarily have to enter the channel name. This can be a random string that is shared between the 2 users.

**Comment by tadaspetra** [comment]
There is now a `Layout.oneToOne` added in the newest version. And like @Meherdeep mentioned, you don't need to prompt your users for a channelName. It can be done behind the scenes in your application code, I sometimes use the `hostUID` as the channel name, but it can be any string as long as both users use the same one
