### ISSUE TITLE
[FEATURE] Windows , mac , Linux, web Support ? 

### ISSUE THREAD

**Issue by Baghdady92** [AgoraIO-Community/VideoUIKit-Flutter#94]
Hello Agora Team 
I love this package and 
i'd like to see it working on all platform 
as we're flutter developers we're expecting to make the app work in all platform 
thanks alot in advance

**Comment by maxxfrazer** [comment]
@Baghdady92 this would need to be fixed in the RTM portion first. It's something we've requested, but I don't see the SDK team adding it before the end of this year unfortunately

RTM SDK: https://github.com/AgoraIO/Agora-Flutter-RTM-SDK
